# Generated by Django 5.1.1 on 2024-10-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=30)),
                ('final_school', models.CharField(max_length=90)),
                ('major', models.CharField(max_length=90)),
                ('degree', models.CharField(max_length=4)),
            ],
        ),
    ]
