# Generated by Django 5.1.1 on 2024-10-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=161, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('capital', models.IntegerField(blank=True, null=True)),
                ('annual_sales', models.IntegerField(blank=True, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('qualification', models.TextField()),
                ('job_description', models.TextField()),
                ('process', models.TextField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
