# Generated by Django 5.1.1 on 2024-10-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_listings',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=161)),
                ('job_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=500)),
                ('job_description', models.CharField(max_length=500)),
                ('process', models.CharField(max_length=500)),
                ('company_profile', models.CharField(max_length=500)),
            ],
        ),
    ]
