# Generated by Django 5.1.1 on 2024-10-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_listings',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('process', models.CharField(max_length=255)),
            ],
        ),
    ]
